config/routes.rb
LearnTesting::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" } 

  resources :authentications, :except => ['index', 'edit', 'update', 'show'] do
    collection do
      get 'pending'
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'

  root :to => "info#index"

  resources :info, :as => "info", :except => ['edit', 'update', 'new', 'create', 'show', 'destroy'] 
  match '/info/about' => 'info#about'
  match '/info/how_assessments_work' => 'info#how_assessments_work'
  match '/info/an_example' => 'info#an_example'
  match '/info/how_disciplines_work' => 'info#how_disciplines_work'
  match '/info/how_categories_work' => 'info#how_categories_work'

  resources :users, :as => "user", :except => ['edit', 'update'] do
    collection do
      get 'pending'
      get 'flash_messages'
      put :update_attribute_on_the_spot
    end

    member do
      put 'approve'
    end
  end

  resources :learnings, :except => ['index'] do
    collection do
      get 'browse'
      get 'search'
      get 'pending_assessments'
      get 'pending_approvals'
    end
    
    member do
      put 'approve'
    end

    resources :assessments, :except => ['destroy', 'index', 'show', 'new', 'create', 'edit']
  end
end

app/controllers/learnings_controller.rb
class LearningsController < ApplicationController
  before_filter :authenticate_user!, :except => ['show', 'search', 'browse']

  def new
    @learning = LearningObjective.new
  end

  def create
    @learning = LearningObjective.new(params[:learning_objective])
    render :template => "learnings/new" and return if @learning.invalid?

    @learning.save

    success_redirect_to t('notice.learning-created'), learning_path(@learning.id)
  end

  def show
    return error_redirect_to t('notice.not-found'), learnings_path unless LearningObjective::exists? params[:id]

    @learning = LearningObjective.find params[:id]

    if user_signed_in?
      @assessment = current_user.get_assessment @learning.id
      @assessment ||= UserAssessments.new(:user_id => current_user.id, :learning_objective_id => @learning.id, :awareness => 'not assessed', :guidance => 'not assessed')
      @assessment.save
    end
  end

  def approve
    return error_redirect_to t('notice.not-found'), learnings_path unless LearningObjective::exists? params[:id]

    @learning = LearningObjective.find params[:id]
    return error_redirect_to t('notice.not-authorised'), learnings_path unless current_user.admin?

    
    @learning.approve!
    
    redirect_to :back
  end

  def edit
    return error_redirect_to t('notice.not-found'), learnings_path unless LearningObjective::exists? params[:id]

    @learning = LearningObjective.find params[:id]
    return error_redirect_to t('notice.not-authorised'), learnings_path unless current_user.admin?
  end

  def update
    return error_redirect_to t('notice.not-found'), learnings_path unless LearningObjective::exists? params[:id]

    @learning = LearningObjective.find params[:id]
    return error_redirect_to t('notice.not-authorised'), learnings_path unless current_user.admin?

    @learning.update_attributes(params[:learning_objective])
    render :template => "learnings/edit" and return if @learning.invalid?

    @learning.save
    success_redirect_to t('notice.learning-updated'), learning_path(@learning.id)
  end

  def search
    @q = ''
    @show_pending = true

    @q = params[:q] unless params[:q].nil?
    @q.strip!
    redirect_to browse_learnings_path and return if @q.blank?

    @page = params[:page]
    @page ||= 1
    @page = @page.to_i

    limit = Rails.application.config.page_size
    offset = (@page - 1) * limit
    @nextpage = search_learnings_path(:q => @q, :page => @page + 1)
    
    
    @disciplines = LearningObjective::DISCIPLINES.select {|d| @q.include? d}
    @categories = LearningObjective::CATEGORIES.select {|c| @q.include? c}

    #don't use search query if it is still within our filter
    query_to_search_for = adjust_query_if_it_was_a_filter("#{@q}", @disciplines, @categories)
    query_to_search_for.strip!

    @learning_objectives = LearningObjective::order(:discipline).order(:category).order(:brief).limit(limit).offset(offset).search(query_to_search_for, @disciplines, @categories, @show_pending)
    @result_count = LearningObjective::order(:discipline).order(:category).order(:brief).search(query_to_search_for, @disciplines, @categories, @show_pending).count
    @pages =  @result_count / limit
    @pages = @pages + 1 if LearningObjective.count % limit != 0
  end

  def pending_assessments
    @learning = LearningObjective::pending_for_user(current_user.id).first
    return success_redirect_to t('notice.no-pending-assessments'), user_index_path if @learning.nil?

    if user_signed_in?
      @assessment = current_user.get_assessment @learning.id
      @assessment ||= UserAssessments.new(:user_id => current_user.id, :learning_objective_id => @learning.id, :awareness => 'not assessed', :guidance => 'not assessed')
      @assessment.save
    end
  end

  def pending_approvals
    @learning_objectives = LearningObjective.pending
  end

  def browse
    @page = params[:page]
    @page ||= 1
    @page = @page.to_i

    limit = Rails.application.config.page_size
    offset = (@page - 1) * limit
    @nextpage = browse_learnings_path(:page => @page + 1)
    
    @learning_objectives = LearningObjective::order(:discipline).order(:category).order(:brief).limit(limit).offset(offset).all
    @result_count = LearningObjective.count
    @pages = @result_count / limit
    @pages = @pages + 1 if LearningObjective.count % limit != 0

    render :template => "learnings/search"
  end
  
  def destroy
    return error_redirect_to t('notice.not-found'), browse_learnings_path unless LearningObjective::exists? params[:id]

    @learning = LearningObjective.find params[:id]
    return error_redirect_to t('notice.not-authorised'), browse_learnings_path unless current_user.admin?

    @learning.user_assessments.each {|ua| ua.delete}
    @learning.delete
    
    success_redirect_to 'Learning Deleted.', browse_learnings_path
  end

  protected
  def adjust_query_if_it_was_a_filter(query, disciplines, categories)
    disciplines.each { |d| query.gsub!(d, "") if query.include? d }
    categories.each { |c| query.gsub!(c, "") if query.include? c }

    query
  end


  def add_querystring_to_array(array, querystring)
    return array if querystring.empty?

    array << querystring
  end


  def get_array_from_query_params(array)
    if array.nil? or array.empty?
      return []
    end

    #as we are using to_param we need to decode the url_encoded strings; if they are encoded
    array = array.each_with_index {|unused, i| CGI::unescape(array[i])} if array.kind_of?(Array)
    array = CGI::unescape(array) if array.kind_of?(String)


    #turn our supplied filters into an array if they are not already one
    #we split on / as we need to cater for rails to_param method
    array = array.split('/') unless array.kind_of?(Array)


    array
  end
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/views/learnings/_page_header.html.haml
%h1
  %span= title
  %small= subtitle
#flash
  =render :partial => '/common/flash'

app/views/learnings/edit.html.haml
.container
  .content
    =render :partial => '/common/page_header', :locals => {:title => t('titles.learning-edit.title'), :subtitle => t('titles.learning-edit.subtitle')}
    .row
      .span16
        = semantic_form_for(@learning, :url => learning_path(@learning.id), :method => :put) do |f|
          .clearfix
            = f.input :brief, :as => :text, :label => I18n.t('form.learning-brief'), :input_html => {:class => 'xxlarge', :rows => 3, :length => 500}
          .clearfix
            = f.input :discipline, :as => :select, :label => I18n.t('form.learning-discipline'), :collection => LearningObjective::DISCIPLINES
            :javascript
              $j("#learning_objective_discipline").attr("class", "chzn-select")
              $j("#learning_objective_discipline").css('width', '90%');
          .clearfix
            = f.input :category, :as => :select, :label => I18n.t('form.learning-category'), :collection => LearningObjective::CATEGORIES
            :javascript
              $j("#learning_objective_category").attr("class", "chzn-select")
              $j("#learning_objective_category").css('width', '90%');
          .actions
            .input
              = f.submit I18n.t('actions.update-learning'), :class => 'btn primary', :id => "update_learning"

app/views/learnings/new.html.haml
.container
  .content
    =render :partial => '/common/page_header', :locals => {:title => t('titles.learning-new.title'), :subtitle => t('titles.learning-new.subtitle')}
    .row
      .span16
        = semantic_form_for(@learning, :url => learnings_path, :method => :post) do |f|
          .clearfix
            = f.input :brief, :as => :text, :label => I18n.t('form.learning-brief'), :input_html => {:class => 'xxlarge', :rows => 3, :length => 500}
          .clearfix
            = f.input :discipline, :as => :select, :label => I18n.t('form.learning-discipline'), :collection => LearningObjective::DISCIPLINES
            :javascript
              $j("#learning_objective_discipline").attr("class", "chzn-select")
              $j("#learning_objective_discipline").css('width', '90%');
          .clearfix
            = f.input :category, :as => :select, :label => I18n.t('form.learning-category'), :collection => LearningObjective::CATEGORIES
            :javascript
              $j("#learning_objective_category").attr("class", "chzn-select")
              $j("#learning_objective_category").css('width', '90%');
          .actions
            .input
              = f.submit I18n.t('actions.create-learning'), :class => 'btn primary', :id => "create_learning"

app/views/learnings/pending_approvals.html.haml
.container
  .content
    - if @learning_objectives.empty?
      %p &nbsp;
      .alert-message.block-message.info
        %p
          %strong There are no learnings to be approved.
    - else
      %p &nbsp;
      .alert-message.block-message.info
        %p
          %strong= "There are #{@learning_objectives.count} learnings pending approval."
    %ul.unstyled#learning_objectives
      - @learning_objectives.each do |lo|
        %li#learning_objective{:style => 'padding-bottom: 1em;'}
          .media-user-discipline
            %h4= "#{lo.discipline} | #{lo.category}"
            %p.large= lo.brief
            - if user_signed_in?
              %p= link_to 'Discuss this', learning_path(lo.id)
            - else
              = link_to 'Sign in to discuss and record your assessment', new_user_session_path

app/views/learnings/pending_assessments.html.haml
.container
  .content
    =render :partial => '/learnings/page_header', :locals => {:title => '', :subtitle => ''}
  .alert-message.block-message.warning
    %strong Pending Assessment.
    %p 
      You have not finished assessing yourself against this learning objective. When you have made your assessment click 'Record Assessment' and
      you will be taken to the next pending assessment.
  .alert-message.block-message.info
    .learning-objective
      %h2= "#{@learning.discipline.upcase} | #{@learning.category.upcase}"
      %p.large= @learning.brief
    - if user_signed_in?
      - if current_user.admin?
        = link_to 'Edit Learning Objective', edit_learning_path(@learning.id), :id => 'edit_learning'
        = link_to 'Delete', learning_path(@learning.id), :method => :delete, :id => 'delete_learning', :class => 'float-right'
        - if @learning.pending?
          %span.float-right &nbsp
          = link_to 'Approve', approve_learning_path(@learning.id), :method => :put, :id => 'approve_learning', :class => 'float-right'
  %hr
  - if user_signed_in?
    .assessment
      = semantic_form_for(@assessment, :url => learning_assessment_path(:learning_id => @learning.id, :id => @assessment.id), :method => :put) do |f|
        .row
          .span8
            %h4 How well do you know this learning objective?
            %p
              By measuring your awareness you can identify whether you need to do more theoretical learning on this topic
          .span8
            %h4 Do you need assistence applying this learning objective?
            %p
              By measuring how often you need guidance you can get a good understanding of where your application of this learning objective sits.
        .row
          .span8
            = f.input :awareness, :as => :select, :label => I18n.t('form.assess-awareness'), :collection => UserAssessments::AWARENESS, :required => false
            :javascript
              $j("#user_assessments_awareness").attr("class", "chzn-select")
              $j("#user_assessments_awareness").css('width', '90%');
          .span8
            = f.input :guidance, :as => :select, :label => I18n.t('form.assess-guidance'), :collection => UserAssessments::GUIDANCE, :required => false
            :javascript
              $j("#user_assessments_guidance").attr("class", "chzn-select")
              $j("#user_assessments_guidance").css('width', '90%');
        .actions
          .input{:style => "min-height: 2em;"}
            = f.submit I18n.t('actions.record-assessment'), :class => 'btn primary float-right', :id => "do_assessment"
  .row
  %hr
  .disqus
    %h4 Discuss this learning objective
    :plain
      <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'learntesting'; // required: replace example with your forum shortname

            // The following are highly recommended additional parameters. Remove the slashes in front to use.
            var disqus_identifier = 'http://learn.cromulent-testing.com/learnings/#{@learning.id}';
            var disqus_url = 'http://learn.cromulent-testing.com/learnings/#{@learning.id}';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/learnings/search.html.haml
.container
  .content
    %p &nbsp;
    .alert-message.block-message.info
      - unless @q.blank?
        %p
          %strong= "Found #{@result_count} matches for the search \"#{@q}\"."
        .clearfix
        %p
          Searching only supports exact matches and does not support multiple terms. You can however
          use the names of disciplines (performance) or a category (lens) to apply broad filters to
          search upon.
        .clearfix
      - else
        %p
          %strong= "Browsing #{@result_count} learnings."
        .clearfix
      %p
        ="Showing page #{@page} of #{@pages} pages."
    %ul.unstyled#learning_objectives
      - @learning_objectives.each do |lo|
        - if user_signed_in?
          - assessment = get_first(current_user.user_assessments.for_learning_objective(lo.id))
        - else
          - assessment = nil
        %li#learning_objective{:style => 'padding-bottom: 1em;'}
          .media-user-discipline
            .row
              .span9
                %h4= "#{lo.discipline} | #{lo.category}"
                %p.large= lo.brief
              .span6
                %h4 Your Assessment
                - if user_signed_in?
                  - unless assessment.nil? or lo.pending or assessment.not_assessed?
                    %p
                      %strong
                        Awareness:
                      %span
                        = assessment.awareness
                    %p
                      %strong
                        Guidance:
                      %span
                        = assessment.guidance
                  - else
                    - if lo.pending
                      %p This learning has not been approved
                    - else
                      %p= link_to 'Assess now', learning_path(lo.id)
                  %p= link_to 'Discuss this', learning_path(lo.id)
                - else
                  = link_to 'Sign in to discuss and record your assessment', new_user_session_path
- if @page.to_i < @pages.to_i
  .actions
    = link_to 'Next Page', @nextpage, :class => 'btn primary'

app/views/learnings/show.html.haml
.container
  .content
    =render :partial => '/learnings/page_header', :locals => {:title => '', :subtitle => ''}
  .alert-message.block-message.info
    .learning-objective
      %h2= "#{@learning.discipline.upcase} | #{@learning.category.upcase}"
      %p.large= @learning.brief
    - if user_signed_in?
      - if current_user.admin?
        = link_to 'Edit Learning Objective', edit_learning_path(@learning.id), :id => 'edit_learning'
        = link_to 'Delete', learning_path(@learning.id), :method => :delete, :id => 'delete_learning', :class => 'float-right'
        - if @learning.pending?
          %span.float-right &nbsp
          = link_to 'Approve', approve_learning_path(@learning.id), :method => :put, :id => 'approve_learning', :class => 'float-right'
  %hr
  - if @learning.pending?
    %p
      %strong This learning is currently pending.
    .clearfix
    %p
      Until we settle on a final description of the learning we won't let you self assess against it.
    .clearfix
    %p
      If you have an opinion about this learning, you should join the discussion below.
    .clearfix
    %p
  - else
    - if user_signed_in?
      .assessment
        = semantic_form_for(@assessment, :url => learning_assessment_path(:learning_id => @learning.id, :id => @assessment.id), :method => :put) do |f|
          .row
            .span8
              %h4 How well do you know this learning objective?
              %p
                By measuring your awareness you can identify whether you need to do more theoretical learning on this topic
            .span8
              %h4 Do you need assistence applying this learning objective?
              %p
                By measuring how often you need guidance you can get a good understanding of where your application of this learning objective sits.
          .row
            .span8
              = f.input :awareness, :as => :select, :label => I18n.t('form.assess-awareness'), :collection => UserAssessments::AWARENESS, :required => false
              :javascript
                $j("#user_assessments_awareness").attr("class", "chzn-select")
                $j("#user_assessments_awareness").css('width', '90%');
            .span8
              = f.input :guidance, :as => :select, :label => I18n.t('form.assess-guidance'), :collection => UserAssessments::GUIDANCE, :required => false
              :javascript
                $j("#user_assessments_guidance").attr("class", "chzn-select")
                $j("#user_assessments_guidance").css('width', '90%');
          .actions
            .input{:style => "min-height: 2em;"}
              = f.submit I18n.t('actions.record-assessment'), :class => 'btn primary float-right', :id => "do_assessment"
  .row
  %hr
  .disqus
    %h4 Discuss this learning objective
    :plain
      <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'learntesting'; // required: replace example with your forum shortname

            // The following are highly recommended additional parameters. Remove the slashes in front to use.
            var disqus_identifier = 'http://learn.cromulent-testing.com/learnings/#{@learning.id}';
            var disqus_url = 'http://learn.cromulent-testing.com/learnings/#{@learning.id}';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>