config/routes.rb
LearnTesting::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" } 

  resources :authentications, :except => ['index', 'edit', 'update', 'show'] do
    collection do
      get 'pending'
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'

  root :to => "info#index"

  resources :info, :as => "info", :except => ['edit', 'update', 'new', 'create', 'show', 'destroy'] 
  match '/info/about' => 'info#about'
  match '/info/how_assessments_work' => 'info#how_assessments_work'
  match '/info/an_example' => 'info#an_example'
  match '/info/how_disciplines_work' => 'info#how_disciplines_work'
  match '/info/how_categories_work' => 'info#how_categories_work'

  resources :users, :as => "user", :except => ['edit', 'update'] do
    collection do
      get 'pending'
      get 'flash_messages'
      put :update_attribute_on_the_spot
    end

    member do
      put 'approve'
    end
  end

  resources :learnings, :except => ['index'] do
    collection do
      get 'browse'
      get 'search'
      get 'pending_assessments'
      get 'pending_approvals'
    end
    
    member do
      put 'approve'
    end

    resources :assessments, :except => ['destroy', 'index', 'show', 'new', 'create', 'edit']
  end
end

app/views/common/_app_menu.html.haml
%ul
  %li
    = link_to 'About', info_about_path
  %li
    = link_to 'Browse', browse_learnings_path
  - if user_signed_in?
    %li
      = link_to 'Pending Assessments', pending_assessments_learnings_path
    - if current_user.admin?
      %li
        = link_to 'Approvals', pending_approvals_learnings_path
    %li
      = link_to 'Propose', new_learning_path

%form.pull-left{:action => search_learnings_path}
  %input{:type => "text", :placeholder => "Search", :id => 'search', :name => 'q', :value => @q}

app/views/common/_auth_menu.html.haml
.pull-right
  %ul
    - if user_signed_in?
      %li
        = link_to(I18n.t('actions.edit-registration'), edit_user_registration_path)
      %li
        = link_to(I18n.t('actions.sign-out'), destroy_user_session_path)
    - else
      %li
        = link_to(I18n.t('actions.sign-up'), new_user_registration_path)
      %li
        = link_to(I18n.t('actions.sign-in'), new_user_session_path)

app/views/common/_definitions.html.haml
.definition{:style => 'width: 35%;'}
  %p.title= t("terminology.#{topic}.label")
  .section_break
  %p.definition_text= t("terminology.#{topic}.definition")

app/views/common/_flash.html.haml
:javascript
  $j(document).ready(function() {
    $j.ajax({
      url: "/users/flash_messages",
      success: function(data)
      {
        if (data["success"])  { flash_message("success", data["success"]); }
        if (data["error"])    { flash_message("error", data["error"]); }
        if (data["warning"])  { flash_message("warning", data["warning"]); }
        if (data["info"])     { flash_message("info", data["info"]); }
      }
    });
  });

app/views/common/_menu.html.haml
.topbar
  .fill
    .container
      = link_to t('text.brand'), root_path, :class => "brand"
      = render :partial => '/common/app_menu'
      = render :partial => '/common/auth_menu'

app/views/common/_notice.html.haml
- id ||= nil
- value ||= false
- with_group ||= false

- if with_group
  .flash
    %p{:class => [keys], :id => id}
      %span= "#{value}".html_safe
- else
  %p{:class => [keys], :id => id}
    %span= "#{value}".html_safe

app/views/common/_page_header.html.haml
.page-header
  %h1
    %span= title
    %small= subtitle
  #flash
    =render :partial => '/common/flash'